### ISSUE TITLE
Crash from java.lang.AbstractMethodError: abstract method "int android.app.IActivityController.appEarlyNotResponding(java.lang.String, int, java.lang.String)

### ISSUE THREAD

**Issue by scottbez1** [linkedin/test-butler#60]
I've noticed occasional crashes like this in test butler:
```04-25 17:19:19.000  1235  1256 W BroadcastQueue: Timeout of broadcast BroadcastRecord{2012bf82 u-1 android.intent.action.TIME_TICK} - receiver=android.os.BinderProxy@9f6ccc8, started 10017ms ago
04-25 17:19:20.398  2362  2447 D [...]
04-25 17:19:20.823  1235  1256 W BroadcastQueue: Receiver during timeout: BroadcastFilter{7d66486 u0 ReceiverList{1b2a5161 1503 com.android.systemui/10012/u0 remote:9f6ccc8}}
04-25 17:19:21.954  2362  3207 D [...]
04-25 17:19:26.111  2362  3243 D [...]
04-25 17:19:27.156  2421  2435 E JavaBinder: *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
04-25 17:19:27.156  2421  2435 E JavaBinder: java.lang.AbstractMethodError: abstract method "int android.app.IActivityController.appEarlyNotResponding(java.lang.String, int, java.lang.String)"
04-25 17:19:27.156  2421  2435 E JavaBinder:     at android.app.IActivityController$Stub.onTransact(IActivityController.java:106)
04-25 17:19:27.156  2421  2435 E JavaBinder:     at android.os.Binder.execTransact(Binder.java:446)
04-25 17:19:29.056  2362  3207 D [...]
04-25 17:19:29.056  2362  2397 D [...]
--------- beginning of crash
04-25 17:19:29.368  2421  2435 E AndroidRuntime: FATAL EXCEPTION: Binder_2
04-25 17:19:29.368  2421  2435 E AndroidRuntime: Process: com.linkedin.android.testbutler, PID: 2421
04-25 17:19:29.368  2421  2435 E AndroidRuntime: java.lang.AbstractMethodError: abstract method "int android.app.IActivityController.appEarlyNotResponding(java.lang.String, int, java.lang.String)"
04-25 17:19:29.368  2421  2435 E AndroidRuntime:     at android.app.IActivityController$Stub.onTransact(IActivityController.java:106)
04-25 17:19:29.368  2421  2435 E AndroidRuntime:     at android.os.Binder.execTransact(Binder.java:446)
04-25 17:19:32.766  1503  1503 I Choreographer: Skipped 100 frames!  The application may be doing too much work on its main thread.
04-25 17:19:41.948  2362  3245 D [...]
04-25 17:19:44.042  2421  2435 V NoDialogActivityController: appCrashed: com.linkedin.android.testbutler:2421 java.lang.AbstractMethodError java.lang.AbstractMethodError: abstract method "int android.app.IActivityController.appEarlyNotResponding(java.lang.String, int, java.lang.String)" java.lang.AbstractMethodError: abstract method "int android.app.IActivityController.appEarlyNotResponding(java.lang.String, int, java.lang.String)"
04-25 17:19:44.042  2421  2435 V NoDialogActivityController:     at android.app.IActivityController$Stub.onTransact(IActivityController.java:106)
04-25 17:19:44.042  2421  2435 V NoDialogActivityController:     at android.os.Binder.execTransact(Binder.java:446)
04-25 17:19:45.158  2362  2447 D [...]
04-25 17:19:46.429  1235  1256 W ActivityManager: Force-killing crashed app com.linkedin.android.testbutler at watcher's request
04-25 17:19:46.531  1235  1256 I ActivityManager: Killing 2421:com.linkedin.android.testbutler/1000 (adj 1): crash
```

If I'm reading that right it sounds like some kind of ANR on the system (some other log messages around the time suggest that things are running pretty slowly on the emulator) but then test butler doesn't implement an abstract callback method for IActivityController which causes a crash?

Running on an API 21 x86 emulator, I believe revision 3.

**Comment by drewhannay** [comment]
This has been released in 1.3.1
